#Rishi Gargi (Id: 11810003)
#Vasanthi Kolachalama (Id: 11810072)
#Vikesh Chopra (Id: 11810127)

try(require("shiny")||install.packages("shiny"))
try(require("tm")||install.packages("tm"))
try(require("wordcloud")||install.packages("wordcloud"))
try(require("memoise")||install.packages("memoise"))
try(require("udpipe")||install.packages("udpipe"))
try(require("textrank")||install.packages("textrank"))
try(require("lattice")||install.packages("lattice"))
try(require("igraph")||install.packages("igraph"))
try(require("ggraph")||install.packages("ggraph"))
try(require("ggplot2")||install.packages("ggplot2"))
try(require("wordcloud")||install.packages("wordcloud"))
try(require("stringr")||install.packages("stringr"))
try(require("wordcloud")||install.packages("wordcloud"))
try(require("shinycssloaders")||install.packages("shinycssloaders"))

library(shiny)
library(tm)
library(wordcloud)
library(memoise)
library(udpipe)
library(textrank)
library(lattice)
library(igraph)
library(ggraph)
library(ggplot2)
library(wordcloud)
library(stringr)
library(wordcloud)
library(shinycssloaders)